language: go

go:
        - "1.16"
        - tip

before_install:
        - sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
        - go get -t -v ./

script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
        - bash <(curl -s https://codecov.io/bash)
